import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'dist/main.js',
	plugins: [{
		name: 'copy-wasm',
		setup(build) {
			build.onEnd(() => {
				// 确保 dist 目录存在
				if (!fs.existsSync('dist')) {
					fs.mkdirSync('dist', { recursive: true });
				}
				const wasmSource = path.join('node_modules', 'sql.js', 'dist', 'sql-wasm.wasm');
				const wasmDest = path.join('dist', 'sql-wasm.wasm');
				fs.copyFileSync(wasmSource, wasmDest);
				console.log('Copied sql-wasm.wasm to dist/');
			});
		},
	}],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
